### ISSUE TITLE
IAP Android - purchase_state: FRAUDULENT with a tester

### ISSUE THREAD

**Issue by lqgioan** [tenjin/tenjin-android-sdk#29]
Using a test account on Google Play store. I buy an item and the app sends an event to the Tenjin.
I can see it on the Live Test tool. But the status is **FRAUDULENT**
<img width="1118" alt="Screen Shot 2020-02-21 at 11 16 54" src="https://user-images.githubusercontent.com/18586774/75004123-b23a0680-549c-11ea-891a-fdc399e42ca5.png">

The **not reveiced** also display on the App dashboard
<img width="1105" alt="Screen Shot 2020-02-21 at 11 25 11" src="https://user-images.githubusercontent.com/18586774/75004180-deee1e00-549c-11ea-9bf1-9de6c44179ff.png">
Are there any problems with my integration? Any helps would be appreciated

**Comment by vanner** [comment]
Can you confirm that you have added the App's public key within the Tenjin dashboard.  Here are the instructions:

https://github.com/tenjin/tenjin-android-sdk#tenjin-purchase-event-instructions

If the app if correctly set up, please email support@tenjin.com and we can help diagnose why these are coming up and FRAUDULENT.

**Comment by lqgioan** [comment]
Hello @vanner ,

I already added the public key within the Tenjin dashboard.
<img width="694" alt="Screen Shot 2020-03-09 at 09 53 42" src="https://user-images.githubusercontent.com/18586774/76179091-3524c600-61ec-11ea-8844-051524a193d3.png">

John,
Thanks

**Comment by Hungsiro506** [comment]
Facing the same issue. Plz help.

**Comment by vanner** [comment]
> Facing the same issue. Plz help.

@Hungsiro506 -  please email support@tenjin.com

**Comment by vanner** [comment]
Issue was resolved through our support channel: support@tenjin.com
